name: Invoke js file
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  open-google:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install axios
        
      - name: Invoke js
        run: node google.js
